# Generated by Django 4.1.4 on 2023-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0019_missing_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status2',
            field=models.CharField(default='n', max_length=50, null=True),
        ),
    ]
