# Generated by Django 4.1.4 on 2023-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0020_complaint_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer_reg',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='officer_reg',
            name='mobileno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
